# -*- coding: utf-8 -*-
"""Period-Pain-Management-Bot.pynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rfoI5jSy7w93Awk_1wyst1cogwDkBwMD

*API key.*

`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`
"""

pip install openai==0.28

import openai

class PeriodPainChatbot:
    def __init__(self, api_key):
        """Initialize the chatbot with OpenAI API key and system context"""
        self.api_key = api_key
        openai.api_key = self.api_key

        # System message to define the chatbot's role and boundaries
        self.system_message = {
            "role": "system",
            "content": """You are a specialized chatbot focused solely on period pain management.
            Your expertise is limited to:
            - Period pain symptoms and management
            - Safe pain relief methods (both medical and natural)
            - Lifestyle adjustments for managing menstrual pain
            - Exercise recommendations during menstruation
            - Diet tips for period pain relief
            - When to seek medical attention
            - Common misconceptions about period pain

            Important guidelines:
            1. Only provide information related to period pain management
            2. Clearly state when a medical professional should be consulted
            3. Don't provide medical diagnoses
            4. Use scientifically backed information
            5. Be empathetic and supportive
            6. Redirect any non-period pain related questions

            If asked about topics outside these boundaries, politely redirect the conversation
            back to period pain management."""
        }

    def get_response(self, user_input):
        """Get a response from the chatbot for the user's input"""
        try:
            # Create messages list for this interaction
            messages = [
                self.system_message,
                {"role": "user", "content": user_input}
            ]

            # Get response from OpenAI
            response = openai.ChatCompletion.create(
                model="gpt-4o",
                messages=messages,
                temperature=0.7,
                max_tokens=500,
                presence_penalty=0.6,
                frequency_penalty=0.3
            )

            return response.choices[0].message['content']

        except Exception as e:
            return f"An error occurred: {str(e)}"

def run_chatbot():
    api_key = input("Please enter your OpenAI API key: ")
    chatbot = PeriodPainChatbot(api_key)

    print("\nPeriod Pain Management Chatbot")
    print("Type 'quit' to exit")
    print("-" * 50)

    while True:
        user_input = input("\nYou: ").strip()

        if user_input.lower() == 'quit':
            break

        response = chatbot.get_response(user_input)
        print("\nChatbot:", response)

if __name__ == "__main__":
    run_chatbot()