# ci.yml - CI Workflow for Development and Main Branches
on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main

name: "CI Workflow"

jobs:
  frontend-ci:
    name: Flutter Frontend CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64

      - name: Get Dependencies
        run: flutter pub get

      - name: Run Analyzer
        run: flutter analyze

      - name: Run Frontend Tests
        run: flutter test
