# -*- coding: utf-8 -*-
"""MensesDataCleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wb8hyskb1hlwICUUAMJ-R2BM5kid9xyt
"""

import pandas as pd

filePath='FedCycleDataClean.xlsx'
df=pd.read_excel(filePath)

"""# Convert all number features to numerics since some are not numerics

"""

# List of columns to convert to numeric
columns_to_convert = [
    'CycleNumber', 'LengthofCycle', 'MeanCycleLength',
    'EstimatedDayofOvulation', 'LengthofLutealPhase',
    'TotalNumberofPeakDays', 'TotalDaysofFertility',
    'LengthofMenses', 'MeanMensesLength', 'Height',
    'Weight', 'BMI'
]
# Convert columns to numeric, coercing errors to NaN
df[columns_to_convert] = df[columns_to_convert].apply(pd.to_numeric, errors='coerce')

"""# Forward filling for Estimated Ovulation, Height, Weight and BMI"""

df['EstimatedDayofOvulation'] = df['EstimatedDayofOvulation'].ffill()
df['Height'] = df['Height'].ffill()
df['Weight'] = df['Weight'].ffill()
df['BMI'] = df['BMI'].ffill()

# fill mean for Null values in LengthofLutealPhase
df['LengthofLutealPhase'].fillna(df['LengthofLutealPhase'].mean(), inplace=True)
df['TotalNumberofPeakDays'].fillna(df['TotalNumberofPeakDays'].mean(), inplace=True)
df['TotalDaysofFertility'].fillna(df['TotalDaysofFertility'].mean(), inplace=True)
df['LengthofMenses'].fillna(df['LengthofMenses'].mean(), inplace=True)

df.isnull().sum()

"""# Applying MinMax Scaler for Height, Weight and BMI"""

# Convert columns to numeric, forcing errors to NaN
cols_to_scale = ['Height', 'Weight', 'BMI']
df[cols_to_scale] = df[cols_to_scale].apply(pd.to_numeric, errors='coerce')

from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
df[cols_to_scale]=scaler.fit_transform(df[cols_to_scale])

#List of columns to check
columns_to_check = [
    'CycleNumber', 'LengthofCycle', 'MeanCycleLength',
    'EstimatedDayofOvulation', 'LengthofLutealPhase',
    'TotalNumberofPeakDays', 'TotalDaysofFertility',
    'LengthofMenses', 'MeanMensesLength', 'Height',
    'Weight', 'BMI'
]

print(df[columns_to_check].dtypes)

df = df.sort_values(by='CycleNumber')

# Create a rolling standard deviation for the 'LengthofCycle' feature, by the intension of feed the model with variability of cycle lengths
window_size = 3  # consider about past 3 cycles
df['CycleVariability'] = df['LengthofCycle'].rolling(window=window_size, min_periods=1).std()

df['CycleVariability'].fillna(0, inplace=True)

df.to_excel('Menses_cleaned.xlsx', index=False)